# Generated by Django 4.2.5 on 2023-11-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_proveedor_vegetable_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rubroventa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
