# Generated by Django 4.2.5 on 2023-11-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_proveedor_rubroventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='preciocompra',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
