# Generated by Django 5.0.1 on 2024-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_compra_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='imagen_nombre',
            field=models.CharField(max_length=100),
        ),
    ]
