# Generated by Django 4.2.5 on 2023-10-21 06:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_carritocompra_compra_detallecompra_historialcompra_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarritoCompra',
            new_name='DetalleCarritoCompra',
        ),
    ]
